// 1: PENDING, 2: PROCESSING, 3: SHIPPED, 4: DELIVERED, 5: CANCELLED, 6: REFUNDED, 7: FAILED

const OrderStatus = {
    PENDING:1,
    PROCESSING:2,
    SHIPPED:3,
    DELIVERED:4,
    CANCELLED:5,
    REFUNDED:6,
    FAILED:7,
}

export default OrderStatus;